// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: cred-checker.proto

package cred_checker

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreditState int32

const (
	CreditState_UNKNOWN      CreditState = 0
	CreditState_CREDITED     CreditState = 1
	CreditState_NOT_CREDITED CreditState = 2
)

// Enum value maps for CreditState.
var (
	CreditState_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREDITED",
		2: "NOT_CREDITED",
	}
	CreditState_value = map[string]int32{
		"UNKNOWN":      0,
		"CREDITED":     1,
		"NOT_CREDITED": 2,
	}
)

func (x CreditState) Enum() *CreditState {
	p := new(CreditState)
	*p = x
	return p
}

func (x CreditState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreditState) Descriptor() protoreflect.EnumDescriptor {
	return file_cred_checker_proto_enumTypes[0].Descriptor()
}

func (CreditState) Type() protoreflect.EnumType {
	return &file_cred_checker_proto_enumTypes[0]
}

func (x CreditState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreditState.Descriptor instead.
func (CreditState) EnumDescriptor() ([]byte, []int) {
	return file_cred_checker_proto_rawDescGZIP(), []int{0}
}

type GetDigitalMinistryCreditsStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inn string `protobuf:"bytes,1,opt,name=inn,proto3" json:"inn,omitempty"`
}

func (x *GetDigitalMinistryCreditsStateRequest) Reset() {
	*x = GetDigitalMinistryCreditsStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cred_checker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDigitalMinistryCreditsStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigitalMinistryCreditsStateRequest) ProtoMessage() {}

func (x *GetDigitalMinistryCreditsStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cred_checker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigitalMinistryCreditsStateRequest.ProtoReflect.Descriptor instead.
func (*GetDigitalMinistryCreditsStateRequest) Descriptor() ([]byte, []int) {
	return file_cred_checker_proto_rawDescGZIP(), []int{0}
}

func (x *GetDigitalMinistryCreditsStateRequest) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

type GetDigitalMinistryCreditsStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inn   string      `protobuf:"bytes,2,opt,name=inn,proto3" json:"inn,omitempty"`
	State CreditState `protobuf:"varint,3,opt,name=state,proto3,enum=cred_checker.CreditState" json:"state,omitempty"`
}

func (x *GetDigitalMinistryCreditsStateResponse) Reset() {
	*x = GetDigitalMinistryCreditsStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cred_checker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDigitalMinistryCreditsStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDigitalMinistryCreditsStateResponse) ProtoMessage() {}

func (x *GetDigitalMinistryCreditsStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cred_checker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDigitalMinistryCreditsStateResponse.ProtoReflect.Descriptor instead.
func (*GetDigitalMinistryCreditsStateResponse) Descriptor() ([]byte, []int) {
	return file_cred_checker_proto_rawDescGZIP(), []int{1}
}

func (x *GetDigitalMinistryCreditsStateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDigitalMinistryCreditsStateResponse) GetInn() string {
	if x != nil {
		return x.Inn
	}
	return ""
}

func (x *GetDigitalMinistryCreditsStateResponse) GetState() CreditState {
	if x != nil {
		return x.State
	}
	return CreditState_UNKNOWN
}

var File_cred_checker_proto protoreflect.FileDescriptor

var file_cred_checker_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x72, 0x65, 0x64, 0x2d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x72, 0x65, 0x64, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x65, 0x72, 0x22, 0x39, 0x0a, 0x25, 0x47, 0x65, 0x74, 0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c,
	0x4d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x79, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6e, 0x6e, 0x22, 0x7f, 0x0a,
	0x26, 0x47, 0x65, 0x74, 0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x4d, 0x69, 0x6e, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x6e, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6e, 0x6e, 0x12, 0x2f, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x63,
	0x72, 0x65, 0x64, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x64,
	0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2a, 0x3a,
	0x0a, 0x0b, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a,
	0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x52,
	0x45, 0x44, 0x49, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x4f, 0x54, 0x5f,
	0x43, 0x52, 0x45, 0x44, 0x49, 0x54, 0x45, 0x44, 0x10, 0x02, 0x32, 0x9b, 0x01, 0x0a, 0x0b, 0x43,
	0x72, 0x65, 0x64, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x8b, 0x01, 0x0a, 0x1e, 0x47,
	0x65, 0x74, 0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x4d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x33, 0x2e,
	0x63, 0x72, 0x65, 0x64, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x4d, 0x69, 0x6e, 0x69, 0x73, 0x74, 0x72, 0x79, 0x43,
	0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x34, 0x2e, 0x63, 0x72, 0x65, 0x64, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x4d, 0x69, 0x6e, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x75, 0x69, 0x74, 0x75, 0x6e, 0x69, 0x6f, 0x6e,
	0x2d, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x72, 0x65, 0x64, 0x2d, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cred_checker_proto_rawDescOnce sync.Once
	file_cred_checker_proto_rawDescData = file_cred_checker_proto_rawDesc
)

func file_cred_checker_proto_rawDescGZIP() []byte {
	file_cred_checker_proto_rawDescOnce.Do(func() {
		file_cred_checker_proto_rawDescData = protoimpl.X.CompressGZIP(file_cred_checker_proto_rawDescData)
	})
	return file_cred_checker_proto_rawDescData
}

var file_cred_checker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cred_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cred_checker_proto_goTypes = []interface{}{
	(CreditState)(0), // 0: cred_checker.CreditState
	(*GetDigitalMinistryCreditsStateRequest)(nil),  // 1: cred_checker.GetDigitalMinistryCreditsStateRequest
	(*GetDigitalMinistryCreditsStateResponse)(nil), // 2: cred_checker.GetDigitalMinistryCreditsStateResponse
}
var file_cred_checker_proto_depIdxs = []int32{
	0, // 0: cred_checker.GetDigitalMinistryCreditsStateResponse.state:type_name -> cred_checker.CreditState
	1, // 1: cred_checker.CredChecker.GetDigitalMinistryCreditsState:input_type -> cred_checker.GetDigitalMinistryCreditsStateRequest
	2, // 2: cred_checker.CredChecker.GetDigitalMinistryCreditsState:output_type -> cred_checker.GetDigitalMinistryCreditsStateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cred_checker_proto_init() }
func file_cred_checker_proto_init() {
	if File_cred_checker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cred_checker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDigitalMinistryCreditsStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cred_checker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDigitalMinistryCreditsStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cred_checker_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cred_checker_proto_goTypes,
		DependencyIndexes: file_cred_checker_proto_depIdxs,
		EnumInfos:         file_cred_checker_proto_enumTypes,
		MessageInfos:      file_cred_checker_proto_msgTypes,
	}.Build()
	File_cred_checker_proto = out.File
	file_cred_checker_proto_rawDesc = nil
	file_cred_checker_proto_goTypes = nil
	file_cred_checker_proto_depIdxs = nil
}
